# Generated by Django 2.2.2 on 2019-08-09 14:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264)),
                ('purpose1', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Job Placement Assistance', 'Job Placement Assistance'), ('Resume Preparation', 'Resume Preparation'), ('Mock Interviewing', 'Mock Interviewing')], default='None', max_length=61, verbose_name='Employment Programs')),
                ('purpose2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Construction', 'Construction'), ('Pre-Apprenticeship', 'Pre-Apprenticeship'), ('Microsoft Office Certification', 'Microsoft Office Certification')], default='None', max_length=62, verbose_name='Workforce Training Programs')),
                ('purpose3', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Public Income Benefits Screening', 'Public Income Benefits Screening'), ('Employment Services and Career Improvement', 'Employment Services and Career Improvement'), ('Financial Workshop', 'Financial Workshop'), ('Financial Coaching', 'Financial Coaching ')], default='None', max_length=113, verbose_name='Financial Opportunity Center')),
                ('purpose4', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Start Saving on a Shoestring', 'Start Saving on a Shoestring'), ('Your Choices and Your Cha-CHING!!', 'Your Choices and Your Cha-CHING!!'), ('Early Career Guide to Becoming Financially Fit', 'Early Career Guide to Becoming Financially Fit'), ('MoneyWISE is a Family Affair)', 'MoneyWISE is a Family Affair'), ('Be a Budget BOSS', 'Be a Budget BOSS'), ('Managing Credit and Debt - The RIGHT Way', 'Managing Credit and Debt - The RIGHT Way'), ("What's in YOUR B.A.G.?  Planning, Saving and Getting Resources for Your  Big, Audacious Goals", 'Whats in YOUR B.A.G.?  Planning, Saving and Getting Resources for Your  Big, Audacious Goals'), ('Miss Independent:  A Womans Guide to Saving and Investing', 'Miss Independent:  A Womans Guide to Saving and Investing'), ('Protecting Your Assets; Protecting Your Family', 'Protecting Your Assets; Protecting Your Family'), ('Your Financially Ever After ', 'Your Financially Ever After')], default='None', max_length=425, verbose_name='Workshops')),
                ('purpose5', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Rental Counseling', 'Rental Counseling'), ('Homebuyer Counseling', 'Homebuyer Counseling'), ('Foreclosure Counseling', 'Foreclosure Counseling')], default='None', max_length=61, verbose_name='Housing')),
                ('purpose6', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('High School Equivalency Program', 'High School Equivalency Program'), ('Job Readiness for Teens)', 'Job Readiness for Teens')], default='None', max_length=56, verbose_name='Young Adults Program')),
                ('purpose7', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Early Childhood Center', 'Early Childhood Center'), ('Newark Kids Code', 'Newark Kids Code')], default='None', max_length=39, verbose_name='Youth Education')),
                ('purpose8', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Youth Programs', 'Youth Programs'), ('Adult Programs', 'Adult Programs'), ('Early Head Start', 'Early Head Start')], default='None', max_length=46, verbose_name='Volunteering')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('referral', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
